name: Deploy Infrastructure

on:
  workflow_dispatch:


jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          AWS_ACCESS_KEY_ID:  '1234'
          AWS_SECRET_ACCESS_KEY:  '123'

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        env:
          AWS_ACCESS_KEY_ID:  '1234'
          AWS_SECRET_ACCESS_KEY:  '123'